apiVersion: v1
kind: Service
metadata:
  name: dev-service
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      name: "http"
      nodePort: 30000
      targetPort: 8080
  selector:
    app: dev-server
